import 'package:flutter/material.dart';

/// Material icon for each preference chip label (no emojis in UI).
IconData preferenceChipIcon(String label) {
  return _icons[label] ?? Icons.restaurant_menu_outlined;
}

const _icons = <String, IconData>{
  // Dietary
  'Vegan': Icons.eco_outlined,
  'Vegetarian': Icons.spa_outlined,
  'Pescatarian': Icons.set_meal_outlined,
  'Flexitarian': Icons.balance_outlined,
  'Halal': Icons.mosque_outlined,
  'Kosher': Icons.star_outline,
  'Gluten-free': Icons.grain_outlined,
  'Wheat-free': Icons.bakery_dining_outlined,
  'Dairy-free': Icons.no_food_outlined,
  'Lactose-free': Icons.icecream_outlined,
  'Egg-free': Icons.egg_alt_outlined,
  'Nut-free': Icons.health_and_safety_outlined,
  'Peanut-free': Icons.do_not_touch_outlined,
  'Tree nut-free': Icons.park_outlined,
  'Soy-free': Icons.grass_outlined,
  'Sesame-free': Icons.local_florist_outlined,
  'Shellfish-free': Icons.water_outlined,
  'Fish-free': Icons.phishing_outlined,
  'No alcohol': Icons.no_drinks_outlined,
  'No red meat': Icons.block_outlined,
  'No pork': Icons.block_outlined,
  'Low FODMAP': Icons.sick_outlined,
  'Diabetic-friendly': Icons.monitor_heart_outlined,
  'Heart-healthy': Icons.favorite_outline,
  'Organic-first': Icons.nature_outlined,
  // Health & lifestyle
  'Low-carb': Icons.trending_down_outlined,
  'Keto': Icons.whatshot_outlined,
  'Paleo': Icons.forest_outlined,
  'Whole30': Icons.calendar_month_outlined,
  'Raw food': Icons.eco_outlined,
  'Mediterranean': Icons.wb_sunny_outlined,
  'Sugar-free': Icons.cake_outlined,
  'High-protein': Icons.fitness_center_outlined,
  'High-fibre': Icons.grass_outlined,
  'Low-sodium': Icons.water_drop_outlined,
  'Calorie-conscious': Icons.scale_outlined,
  'Anti-inflammatory': Icons.healing_outlined,
  'Carnivore': Icons.set_meal_outlined,
  'Intermittent fasting': Icons.schedule_outlined,
  'DASH diet': Icons.medical_services_outlined,
  // Cuisines
  'Italian': Icons.ramen_dining_outlined,
  'French': Icons.breakfast_dining_outlined,
  'Spanish': Icons.tapas_outlined,
  'Greek': Icons.lunch_dining_outlined,
  'Turkish': Icons.kebab_dining_outlined,
  'Lebanese': Icons.dinner_dining_outlined,
  'Middle Eastern': Icons.flatware_outlined,
  'Moroccan': Icons.soup_kitchen_outlined,
  'Persian': Icons.rice_bowl_outlined,
  'Indian': Icons.local_dining_outlined,
  'Pakistani': Icons.local_dining_outlined,
  'Bangladeshi': Icons.local_dining_outlined,
  'Thai': Icons.ramen_dining_outlined,
  'Vietnamese': Icons.ramen_dining_outlined,
  'Chinese': Icons.takeout_dining_outlined,
  'Japanese': Icons.set_meal_outlined,
  'Korean': Icons.ramen_dining_outlined,
  'Indonesian': Icons.rice_bowl_outlined,
  'Malaysian': Icons.ramen_dining_outlined,
  'Filipino': Icons.rice_bowl_outlined,
  'Singaporean': Icons.set_meal_outlined,
  'Mexican': Icons.local_pizza_outlined,
  'Tex-Mex': Icons.lunch_dining_outlined,
  'Caribbean': Icons.beach_access_outlined,
  'Brazilian': Icons.outdoor_grill_outlined,
  'Peruvian': Icons.terrain_outlined,
  'Argentinian': Icons.outdoor_grill_outlined,
  'American': Icons.fastfood_outlined,
  'Southern US': Icons.restaurant_outlined,
  'Cajun / Creole': Icons.set_meal_outlined,
  'British': Icons.local_cafe_outlined,
  'Irish': Icons.agriculture_outlined,
  'German': Icons.bakery_dining_outlined,
  'Scandinavian': Icons.set_meal_outlined,
  'Polish': Icons.dining_outlined,
  'Russian': Icons.soup_kitchen_outlined,
  'Hungarian': Icons.soup_kitchen_outlined,
  'Ethiopian': Icons.flatware_outlined,
  'West African': Icons.rice_bowl_outlined,
  'South African': Icons.outdoor_grill_outlined,
  'Australian': Icons.public_outlined,
  'Fusion': Icons.auto_awesome_outlined,
  'International': Icons.language_outlined,
};
